export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Games } from "./Games";
export { default as Projects } from "./Projects";
export { default as Project } from "./Project";
export { default as BoxLink } from "./BoxLink";
export { default as ProjectPreview } from "./ProjectPreview";
